import { motion } from 'framer-motion';

// Extracted from src/assets/nepal-outline.svg (generated by scripts/generateEarthTexture.mjs
// from the same public-domain Natural Earth data as the globe texture) so the outline can be
// drawn stroke-by-stroke with Framer Motion instead of loaded as a static <img>.
const NEPAL_PATH_D =
  'M595.993,239.563L590.383,271.59L600,318.689L591.451,348.079L529.742,349.335L440.516,332.002L383.081,324.969L340.338,287.164L238.557,277.619L141.852,235.921L71.861,199.623L0,171.49L28.851,102.035L75.868,68.375L106.589,50.665L166.162,73.524L240.962,121.879L282.903,132.429L307.747,168.098L365.45,182.793L425.557,215.323L509.439,232.404Z';

export default function AnimatedNepalMap({ className = '' }) {
  return (
    <svg
      viewBox="0 0 600 400"
      className={className}
      aria-hidden="true"
      style={{ overflow: 'visible' }}
    >
      {/* Draws in bright and bold (the arrival beat), then eases down to a subtle
          resting backdrop once the hero copy takes over the foreground. */}
      <motion.path
        d={NEPAL_PATH_D}
        fill="rgba(244,208,63,0.14)"
        stroke="#f4d03f"
        strokeWidth={2.2}
        strokeLinejoin="round"
        initial={{ pathLength: 0, opacity: 0, strokeOpacity: 1 }}
        animate={{ pathLength: 1, opacity: [0, 1, 1, 0.4], strokeOpacity: [1, 1, 1, 0.5] }}
        transition={{
          pathLength: { duration: 2.2, ease: [0.4, 0, 0.2, 1] },
          opacity: { duration: 3.4, times: [0, 0.35, 0.65, 1], ease: [0.4, 0, 0.2, 1] },
          strokeOpacity: { duration: 3.4, times: [0, 0.35, 0.65, 1], ease: [0.4, 0, 0.2, 1] },
        }}
        style={{ filter: 'drop-shadow(0 0 22px rgba(244,208,63,0.5))' }}
      />
      <motion.path
        d={NEPAL_PATH_D}
        fill="rgba(244,208,63,0.16)"
        stroke="none"
        initial={{ opacity: 0 }}
        animate={{ opacity: [0, 0.9, 0.35] }}
        transition={{ duration: 3, times: [0, 0.4, 1], delay: 1.8, ease: [0.4, 0, 0.2, 1] }}
      />
    </svg>
  );
}
