/* AUTO-GENERATED by build_data.py - do not edit by hand.
   Regenerate with: python build_data.py                       */
window.NF_DATA = {
  "incidents": [
    {
      "avg_tone": -2.2623,
      "event_days": 61,
      "total_events": 1277,
      "country": "India",
      "incident": "2015 Earthquake"
    },
    {
      "avg_tone": -0.2866,
      "event_days": 60,
      "total_events": 1849,
      "country": "China",
      "incident": "2015 Earthquake"
    },
    {
      "avg_tone": -2.4345,
      "event_days": 95,
      "total_events": 859,
      "country": "India",
      "incident": "2015 Blockade"
    },
    {
      "avg_tone": -0.445,
      "event_days": 90,
      "total_events": 1366,
      "country": "China",
      "incident": "2015 Blockade"
    },
    {
      "avg_tone": -2.2958,
      "event_days": 67,
      "total_events": 568,
      "country": "India",
      "incident": "2025 Gen-Z Protest"
    },
    {
      "avg_tone": -0.7109,
      "event_days": 50,
      "total_events": 368,
      "country": "China",
      "incident": "2025 Gen-Z Protest"
    }
  ],
  "daily": [
    {
      "event_date": "2015-09-09",
      "avg_tone": 0.6199,
      "total_events": 1,
      "avg_conflict_score": 0.0,
      "total_articles": 5,
      "rolling_avg_30d": null,
      "spike_ratio": null,
      "is_spike": null
    },
    {
      "event_date": "2024-09-01",
      "avg_tone": 1.743,
      "total_events": 9,
      "avg_conflict_score": 2.7667,
      "total_articles": 30,
      "rolling_avg_30d": 1.0,
      "spike_ratio": 9.0,
      "is_spike": true
    },
    {
      "event_date": "2024-09-04",
      "avg_tone": -4.186,
      "total_events": 1,
      "avg_conflict_score": -5.0,
      "total_articles": 5,
      "rolling_avg_30d": 5.0,
      "spike_ratio": 0.2,
      "is_spike": false
    },
    {
      "event_date": "2024-09-05",
      "avg_tone": -9.0909,
      "total_events": 4,
      "avg_conflict_score": -3.325,
      "total_articles": 12,
      "rolling_avg_30d": 3.67,
      "spike_ratio": 1.09,
      "is_spike": false
    },
    {
      "event_date": "2024-09-08",
      "avg_tone": -14.1809,
      "total_events": 2,
      "avg_conflict_score": -6.5,
      "total_articles": 5,
      "rolling_avg_30d": 3.75,
      "spike_ratio": 0.53,
      "is_spike": false
    },
    {
      "event_date": "2024-09-10",
      "avg_tone": -5.2754,
      "total_events": 1,
      "avg_conflict_score": -2.0,
      "total_articles": 3,
      "rolling_avg_30d": 3.4,
      "spike_ratio": 0.29,
      "is_spike": false
    },
    {
      "event_date": "2024-09-11",
      "avg_tone": -7.5953,
      "total_events": 6,
      "avg_conflict_score": -0.1667,
      "total_articles": 13,
      "rolling_avg_30d": 3.0,
      "spike_ratio": 2.0,
      "is_spike": false
    },
    {
      "event_date": "2024-09-12",
      "avg_tone": 0.0389,
      "total_events": 2,
      "avg_conflict_score": -2.0,
      "total_articles": 10,
      "rolling_avg_30d": 3.43,
      "spike_ratio": 0.58,
      "is_spike": false
    },
    {
      "event_date": "2024-09-13",
      "avg_tone": -2.137,
      "total_events": 3,
      "avg_conflict_score": 5.6667,
      "total_articles": 10,
      "rolling_avg_30d": 3.25,
      "spike_ratio": 0.92,
      "is_spike": false
    },
    {
      "event_date": "2024-09-14",
      "avg_tone": 0.796,
      "total_events": 6,
      "avg_conflict_score": 7.0,
      "total_articles": 20,
      "rolling_avg_30d": 3.22,
      "spike_ratio": 1.86,
      "is_spike": false
    },
    {
      "event_date": "2024-09-15",
      "avg_tone": -2.6399,
      "total_events": 5,
      "avg_conflict_score": 6.8,
      "total_articles": 12,
      "rolling_avg_30d": 3.5,
      "spike_ratio": 1.43,
      "is_spike": false
    },
    {
      "event_date": "2024-09-16",
      "avg_tone": -5.0026,
      "total_events": 3,
      "avg_conflict_score": 9.0,
      "total_articles": 9,
      "rolling_avg_30d": 3.64,
      "spike_ratio": 0.82,
      "is_spike": false
    },
    {
      "event_date": "2024-09-17",
      "avg_tone": -0.7692,
      "total_events": 2,
      "avg_conflict_score": 2.35,
      "total_articles": 10,
      "rolling_avg_30d": 3.58,
      "spike_ratio": 0.56,
      "is_spike": false
    },
    {
      "event_date": "2024-09-18",
      "avg_tone": -0.8929,
      "total_events": 2,
      "avg_conflict_score": 5.0,
      "total_articles": 8,
      "rolling_avg_30d": 3.46,
      "spike_ratio": 0.58,
      "is_spike": false
    },
    {
      "event_date": "2024-09-19",
      "avg_tone": -3.9039,
      "total_events": 2,
      "avg_conflict_score": 2.35,
      "total_articles": 10,
      "rolling_avg_30d": 3.36,
      "spike_ratio": 0.6,
      "is_spike": false
    },
    {
      "event_date": "2024-09-21",
      "avg_tone": -7.4074,
      "total_events": 1,
      "avg_conflict_score": -4.0,
      "total_articles": 4,
      "rolling_avg_30d": 3.27,
      "spike_ratio": 0.31,
      "is_spike": false
    },
    {
      "event_date": "2024-09-22",
      "avg_tone": -6.0411,
      "total_events": 1,
      "avg_conflict_score": -4.0,
      "total_articles": 4,
      "rolling_avg_30d": 3.13,
      "spike_ratio": 0.32,
      "is_spike": false
    },
    {
      "event_date": "2024-09-24",
      "avg_tone": -2.0534,
      "total_events": 7,
      "avg_conflict_score": 1.8286,
      "total_articles": 23,
      "rolling_avg_30d": 3.0,
      "spike_ratio": 2.33,
      "is_spike": false
    },
    {
      "event_date": "2024-09-25",
      "avg_tone": -7.5756,
      "total_events": 2,
      "avg_conflict_score": -8.6,
      "total_articles": 9,
      "rolling_avg_30d": 3.22,
      "spike_ratio": 0.62,
      "is_spike": false
    },
    {
      "event_date": "2024-09-26",
      "avg_tone": -7.1792,
      "total_events": 3,
      "avg_conflict_score": -8.8,
      "total_articles": 11,
      "rolling_avg_30d": 3.16,
      "spike_ratio": 0.95,
      "is_spike": false
    },
    {
      "event_date": "2024-09-27",
      "avg_tone": -8.4977,
      "total_events": 2,
      "avg_conflict_score": -5.0,
      "total_articles": 6,
      "rolling_avg_30d": 3.15,
      "spike_ratio": 0.63,
      "is_spike": false
    },
    {
      "event_date": "2024-09-28",
      "avg_tone": -6.782,
      "total_events": 4,
      "avg_conflict_score": -0.25,
      "total_articles": 6,
      "rolling_avg_30d": 3.1,
      "spike_ratio": 1.29,
      "is_spike": false
    },
    {
      "event_date": "2024-09-29",
      "avg_tone": -8.8435,
      "total_events": 2,
      "avg_conflict_score": -5.0,
      "total_articles": 10,
      "rolling_avg_30d": 3.14,
      "spike_ratio": 0.64,
      "is_spike": false
    },
    {
      "event_date": "2024-10-02",
      "avg_tone": -1.0649,
      "total_events": 1,
      "avg_conflict_score": -2.0,
      "total_articles": 2,
      "rolling_avg_30d": 3.09,
      "spike_ratio": 0.32,
      "is_spike": false
    },
    {
      "event_date": "2024-10-04",
      "avg_tone": -2.4793,
      "total_events": 2,
      "avg_conflict_score": -10.0,
      "total_articles": 5,
      "rolling_avg_30d": 3.0,
      "spike_ratio": 0.67,
      "is_spike": false
    },
    {
      "event_date": "2024-10-07",
      "avg_tone": -6.5781,
      "total_events": 9,
      "avg_conflict_score": 0.4667,
      "total_articles": 26,
      "rolling_avg_30d": 2.96,
      "spike_ratio": 3.04,
      "is_spike": true
    },
    {
      "event_date": "2024-10-08",
      "avg_tone": 0.565,
      "total_events": 2,
      "avg_conflict_score": 1.9,
      "total_articles": 5,
      "rolling_avg_30d": 3.19,
      "spike_ratio": 0.63,
      "is_spike": false
    },
    {
      "event_date": "2024-10-09",
      "avg_tone": -1.3514,
      "total_events": 1,
      "avg_conflict_score": 1.9,
      "total_articles": 5,
      "rolling_avg_30d": 3.15,
      "spike_ratio": 0.32,
      "is_spike": false
    },
    {
      "event_date": "2024-10-13",
      "avg_tone": -6.8702,
      "total_events": 2,
      "avg_conflict_score": 1.0,
      "total_articles": 20,
      "rolling_avg_30d": 3.07,
      "spike_ratio": 0.65,
      "is_spike": false
    },
    {
      "event_date": "2024-10-14",
      "avg_tone": -1.8838,
      "total_events": 1,
      "avg_conflict_score": 0.4,
      "total_articles": 4,
      "rolling_avg_30d": 3.03,
      "spike_ratio": 0.33,
      "is_spike": false
    },
    {
      "event_date": "2024-10-16",
      "avg_tone": -3.6847,
      "total_events": 6,
      "avg_conflict_score": 2.6,
      "total_articles": 12,
      "rolling_avg_30d": 2.97,
      "spike_ratio": 2.02,
      "is_spike": false
    },
    {
      "event_date": "2024-10-17",
      "avg_tone": 0.0,
      "total_events": 2,
      "avg_conflict_score": -0.25,
      "total_articles": 4,
      "rolling_avg_30d": 3.13,
      "spike_ratio": 0.64,
      "is_spike": false
    },
    {
      "event_date": "2024-10-21",
      "avg_tone": -0.1369,
      "total_events": 2,
      "avg_conflict_score": -5.0,
      "total_articles": 2,
      "rolling_avg_30d": 2.9,
      "spike_ratio": 0.69,
      "is_spike": false
    },
    {
      "event_date": "2024-10-29",
      "avg_tone": -0.5515,
      "total_events": 1,
      "avg_conflict_score": 1.9,
      "total_articles": 1,
      "rolling_avg_30d": 2.93,
      "spike_ratio": 0.34,
      "is_spike": false
    },
    {
      "event_date": "2024-10-30",
      "avg_tone": -1.7118,
      "total_events": 2,
      "avg_conflict_score": 2.35,
      "total_articles": 4,
      "rolling_avg_30d": 2.83,
      "spike_ratio": 0.71,
      "is_spike": false
    },
    {
      "event_date": "2024-10-31",
      "avg_tone": -1.8233,
      "total_events": 2,
      "avg_conflict_score": 2.35,
      "total_articles": 4,
      "rolling_avg_30d": 2.83,
      "spike_ratio": 0.71,
      "is_spike": false
    },
    {
      "event_date": "2024-11-01",
      "avg_tone": -1.8182,
      "total_events": 2,
      "avg_conflict_score": 2.35,
      "total_articles": 4,
      "rolling_avg_30d": 2.87,
      "spike_ratio": 0.7,
      "is_spike": false
    },
    {
      "event_date": "2024-11-02",
      "avg_tone": 8.3916,
      "total_events": 1,
      "avg_conflict_score": -0.3,
      "total_articles": 4,
      "rolling_avg_30d": 2.73,
      "spike_ratio": 0.37,
      "is_spike": false
    },
    {
      "event_date": "2024-11-03",
      "avg_tone": -2.3817,
      "total_events": 4,
      "avg_conflict_score": 2.025,
      "total_articles": 24,
      "rolling_avg_30d": 2.7,
      "spike_ratio": 1.48,
      "is_spike": false
    },
    {
      "event_date": "2024-11-04",
      "avg_tone": -4.3187,
      "total_events": 4,
      "avg_conflict_score": 1.15,
      "total_articles": 16,
      "rolling_avg_30d": 2.73,
      "spike_ratio": 1.47,
      "is_spike": false
    },
    {
      "event_date": "2024-11-07",
      "avg_tone": -1.0877,
      "total_events": 2,
      "avg_conflict_score": 3.0,
      "total_articles": 9,
      "rolling_avg_30d": 2.67,
      "spike_ratio": 0.75,
      "is_spike": false
    },
    {
      "event_date": "2024-11-09",
      "avg_tone": -2.8257,
      "total_events": 4,
      "avg_conflict_score": 2.35,
      "total_articles": 8,
      "rolling_avg_30d": 2.57,
      "spike_ratio": 1.56,
      "is_spike": false
    },
    {
      "event_date": "2024-11-11",
      "avg_tone": -4.0816,
      "total_events": 1,
      "avg_conflict_score": -4.0,
      "total_articles": 2,
      "rolling_avg_30d": 2.6,
      "spike_ratio": 0.38,
      "is_spike": false
    },
    {
      "event_date": "2025-08-05",
      "avg_tone": -3.4175,
      "total_events": 2,
      "avg_conflict_score": -0.5,
      "total_articles": 10,
      "rolling_avg_30d": 2.57,
      "spike_ratio": 0.78,
      "is_spike": false
    },
    {
      "event_date": "2025-08-06",
      "avg_tone": -3.1891,
      "total_events": 2,
      "avg_conflict_score": -0.5,
      "total_articles": 10,
      "rolling_avg_30d": 2.57,
      "spike_ratio": 0.78,
      "is_spike": false
    },
    {
      "event_date": "2025-08-11",
      "avg_tone": -9.894,
      "total_events": 1,
      "avg_conflict_score": -5.0,
      "total_articles": 5,
      "rolling_avg_30d": 2.57,
      "spike_ratio": 0.39,
      "is_spike": false
    },
    {
      "event_date": "2025-08-17",
      "avg_tone": -5.0952,
      "total_events": 3,
      "avg_conflict_score": 0.0,
      "total_articles": 15,
      "rolling_avg_30d": 2.57,
      "spike_ratio": 1.17,
      "is_spike": false
    },
    {
      "event_date": "2025-08-22",
      "avg_tone": -4.3376,
      "total_events": 1,
      "avg_conflict_score": 1.0,
      "total_articles": 8,
      "rolling_avg_30d": 2.63,
      "spike_ratio": 0.38,
      "is_spike": false
    },
    {
      "event_date": "2025-08-25",
      "avg_tone": 3.1746,
      "total_events": 1,
      "avg_conflict_score": 4.0,
      "total_articles": 10,
      "rolling_avg_30d": 2.43,
      "spike_ratio": 0.41,
      "is_spike": false
    },
    {
      "event_date": "2025-08-30",
      "avg_tone": 0.6199,
      "total_events": 2,
      "avg_conflict_score": 1.0,
      "total_articles": 4,
      "rolling_avg_30d": 2.4,
      "spike_ratio": 0.83,
      "is_spike": false
    },
    {
      "event_date": "2025-08-31",
      "avg_tone": -5.1991,
      "total_events": 4,
      "avg_conflict_score": -5.375,
      "total_articles": 26,
      "rolling_avg_30d": 2.37,
      "spike_ratio": 1.69,
      "is_spike": false
    },
    {
      "event_date": "2025-09-01",
      "avg_tone": -1.2954,
      "total_events": 221,
      "avg_conflict_score": 0.7792,
      "total_articles": 834,
      "rolling_avg_30d": 2.43,
      "spike_ratio": 90.95,
      "is_spike": true
    },
    {
      "event_date": "2025-09-02",
      "avg_tone": -1.4363,
      "total_events": 184,
      "avg_conflict_score": 1.0348,
      "total_articles": 832,
      "rolling_avg_30d": 9.67,
      "spike_ratio": 19.03,
      "is_spike": true
    },
    {
      "event_date": "2025-09-03",
      "avg_tone": -0.3253,
      "total_events": 272,
      "avg_conflict_score": 1.5261,
      "total_articles": 1039,
      "rolling_avg_30d": 15.73,
      "spike_ratio": 17.29,
      "is_spike": true
    },
    {
      "event_date": "2025-09-04",
      "avg_tone": -1.3179,
      "total_events": 299,
      "avg_conflict_score": 0.8572,
      "total_articles": 1597,
      "rolling_avg_30d": 24.77,
      "spike_ratio": 12.07,
      "is_spike": true
    },
    {
      "event_date": "2025-09-05",
      "avg_tone": -1.8522,
      "total_events": 233,
      "avg_conflict_score": 0.9536,
      "total_articles": 971,
      "rolling_avg_30d": 34.67,
      "spike_ratio": 6.72,
      "is_spike": true
    },
    {
      "event_date": "2025-09-06",
      "avg_tone": 0.5569,
      "total_events": 188,
      "avg_conflict_score": 1.6723,
      "total_articles": 991,
      "rolling_avg_30d": 42.13,
      "spike_ratio": 4.46,
      "is_spike": true
    },
    {
      "event_date": "2025-09-07",
      "avg_tone": -1.6002,
      "total_events": 172,
      "avg_conflict_score": 0.8698,
      "total_articles": 988,
      "rolling_avg_30d": 48.33,
      "spike_ratio": 3.56,
      "is_spike": true
    },
    {
      "event_date": "2025-09-08",
      "avg_tone": -7.6609,
      "total_events": 675,
      "avg_conflict_score": -3.1019,
      "total_articles": 3698,
      "rolling_avg_30d": 54.03,
      "spike_ratio": 12.49,
      "is_spike": true
    },
    {
      "event_date": "2025-09-09",
      "avg_tone": -8.1429,
      "total_events": 2370,
      "avg_conflict_score": -1.0768,
      "total_articles": 11697,
      "rolling_avg_30d": 76.47,
      "spike_ratio": 30.99,
      "is_spike": true
    },
    {
      "event_date": "2025-09-10",
      "avg_tone": -5.9853,
      "total_events": 1944,
      "avg_conflict_score": -1.159,
      "total_articles": 9749,
      "rolling_avg_30d": 155.43,
      "spike_ratio": 12.51,
      "is_spike": true
    },
    {
      "event_date": "2025-09-11",
      "avg_tone": -4.7834,
      "total_events": 1653,
      "avg_conflict_score": -0.5688,
      "total_articles": 7104,
      "rolling_avg_30d": 220.03,
      "spike_ratio": 7.51,
      "is_spike": true
    },
    {
      "event_date": "2025-09-12",
      "avg_tone": -4.6002,
      "total_events": 1395,
      "avg_conflict_score": -0.2103,
      "total_articles": 5887,
      "rolling_avg_30d": 275.07,
      "spike_ratio": 5.07,
      "is_spike": true
    },
    {
      "event_date": "2025-09-13",
      "avg_tone": -2.8716,
      "total_events": 895,
      "avg_conflict_score": 0.2771,
      "total_articles": 3476,
      "rolling_avg_30d": 321.5,
      "spike_ratio": 2.78,
      "is_spike": false
    },
    {
      "event_date": "2025-09-14",
      "avg_tone": -3.4076,
      "total_events": 685,
      "avg_conflict_score": 0.4108,
      "total_articles": 2819,
      "rolling_avg_30d": 351.3,
      "spike_ratio": 1.95,
      "is_spike": false
    },
    {
      "event_date": "2025-09-15",
      "avg_tone": -4.309,
      "total_events": 563,
      "avg_conflict_score": -0.0602,
      "total_articles": 2679,
      "rolling_avg_30d": 374.07,
      "spike_ratio": 1.51,
      "is_spike": false
    },
    {
      "event_date": "2025-09-16",
      "avg_tone": -5.0717,
      "total_events": 466,
      "avg_conflict_score": -0.7738,
      "total_articles": 2210,
      "rolling_avg_30d": 392.77,
      "spike_ratio": 1.19,
      "is_spike": false
    },
    {
      "event_date": "2025-09-17",
      "avg_tone": -2.3078,
      "total_events": 354,
      "avg_conflict_score": 0.4311,
      "total_articles": 1393,
      "rolling_avg_30d": 408.23,
      "spike_ratio": 0.87,
      "is_spike": false
    },
    {
      "event_date": "2025-09-18",
      "avg_tone": -1.4195,
      "total_events": 395,
      "avg_conflict_score": 0.3451,
      "total_articles": 1490,
      "rolling_avg_30d": 420.0,
      "spike_ratio": 0.94,
      "is_spike": false
    },
    {
      "event_date": "2025-09-19",
      "avg_tone": -1.7149,
      "total_events": 497,
      "avg_conflict_score": 0.3362,
      "total_articles": 1950,
      "rolling_avg_30d": 433.03,
      "spike_ratio": 1.15,
      "is_spike": false
    },
    {
      "event_date": "2025-09-20",
      "avg_tone": -3.3307,
      "total_events": 128,
      "avg_conflict_score": -0.6164,
      "total_articles": 616,
      "rolling_avg_30d": 449.47,
      "spike_ratio": 0.28,
      "is_spike": false
    },
    {
      "event_date": "2025-09-21",
      "avg_tone": -1.8293,
      "total_events": 222,
      "avg_conflict_score": 0.4405,
      "total_articles": 872,
      "rolling_avg_30d": 453.67,
      "spike_ratio": 0.49,
      "is_spike": false
    },
    {
      "event_date": "2025-09-22",
      "avg_tone": -1.5595,
      "total_events": 252,
      "avg_conflict_score": 0.731,
      "total_articles": 1068,
      "rolling_avg_30d": 460.93,
      "spike_ratio": 0.55,
      "is_spike": false
    },
    {
      "event_date": "2025-09-23",
      "avg_tone": -1.0647,
      "total_events": 221,
      "avg_conflict_score": 1.0674,
      "total_articles": 1196,
      "rolling_avg_30d": 469.3,
      "spike_ratio": 0.47,
      "is_spike": false
    },
    {
      "event_date": "2025-09-24",
      "avg_tone": -2.4574,
      "total_events": 253,
      "avg_conflict_score": 0.5166,
      "total_articles": 937,
      "rolling_avg_30d": 476.6,
      "spike_ratio": 0.53,
      "is_spike": false
    },
    {
      "event_date": "2025-09-25",
      "avg_tone": -4.2233,
      "total_events": 239,
      "avg_conflict_score": -0.3967,
      "total_articles": 1035,
      "rolling_avg_30d": 484.97,
      "spike_ratio": 0.49,
      "is_spike": false
    },
    {
      "event_date": "2025-09-26",
      "avg_tone": -2.7812,
      "total_events": 270,
      "avg_conflict_score": 0.9019,
      "total_articles": 1019,
      "rolling_avg_30d": 492.9,
      "spike_ratio": 0.55,
      "is_spike": false
    },
    {
      "event_date": "2025-09-27",
      "avg_tone": -4.9496,
      "total_events": 140,
      "avg_conflict_score": 0.1086,
      "total_articles": 576,
      "rolling_avg_30d": 501.8,
      "spike_ratio": 0.28,
      "is_spike": false
    },
    {
      "event_date": "2025-09-28",
      "avg_tone": -4.0509,
      "total_events": 137,
      "avg_conflict_score": 0.0022,
      "total_articles": 555,
      "rolling_avg_30d": 506.43,
      "spike_ratio": 0.27,
      "is_spike": false
    },
    {
      "event_date": "2025-09-29",
      "avg_tone": -4.0615,
      "total_events": 167,
      "avg_conflict_score": 0.0186,
      "total_articles": 825,
      "rolling_avg_30d": 510.97,
      "spike_ratio": 0.33,
      "is_spike": false
    },
    {
      "event_date": "2025-09-30",
      "avg_tone": -2.9779,
      "total_events": 147,
      "avg_conflict_score": -1.2327,
      "total_articles": 633,
      "rolling_avg_30d": 516.47,
      "spike_ratio": 0.28,
      "is_spike": false
    },
    {
      "event_date": "2025-10-01",
      "avg_tone": -2.2722,
      "total_events": 176,
      "avg_conflict_score": -0.1102,
      "total_articles": 803,
      "rolling_avg_30d": 521.23,
      "spike_ratio": 0.34,
      "is_spike": false
    },
    {
      "event_date": "2025-10-02",
      "avg_tone": -1.4021,
      "total_events": 147,
      "avg_conflict_score": -0.1054,
      "total_articles": 613,
      "rolling_avg_30d": 519.73,
      "spike_ratio": 0.28,
      "is_spike": false
    },
    {
      "event_date": "2025-10-03",
      "avg_tone": -2.547,
      "total_events": 100,
      "avg_conflict_score": -0.146,
      "total_articles": 427,
      "rolling_avg_30d": 518.5,
      "spike_ratio": 0.19,
      "is_spike": false
    },
    {
      "event_date": "2025-10-04",
      "avg_tone": -1.7706,
      "total_events": 119,
      "avg_conflict_score": 0.563,
      "total_articles": 442,
      "rolling_avg_30d": 512.77,
      "spike_ratio": 0.23,
      "is_spike": false
    },
    {
      "event_date": "2025-10-05",
      "avg_tone": -6.2266,
      "total_events": 162,
      "avg_conflict_score": -0.25,
      "total_articles": 713,
      "rolling_avg_30d": 506.77,
      "spike_ratio": 0.32,
      "is_spike": false
    },
    {
      "event_date": "2025-10-06",
      "avg_tone": -3.603,
      "total_events": 171,
      "avg_conflict_score": 0.8766,
      "total_articles": 728,
      "rolling_avg_30d": 504.4,
      "spike_ratio": 0.34,
      "is_spike": false
    },
    {
      "event_date": "2025-10-07",
      "avg_tone": -3.9491,
      "total_events": 195,
      "avg_conflict_score": -0.3949,
      "total_articles": 693,
      "rolling_avg_30d": 503.83,
      "spike_ratio": 0.39,
      "is_spike": false
    },
    {
      "event_date": "2025-10-08",
      "avg_tone": -2.0008,
      "total_events": 184,
      "avg_conflict_score": 1.1304,
      "total_articles": 684,
      "rolling_avg_30d": 504.6,
      "spike_ratio": 0.36,
      "is_spike": false
    },
    {
      "event_date": "2025-10-09",
      "avg_tone": -1.7419,
      "total_events": 152,
      "avg_conflict_score": 1.575,
      "total_articles": 681,
      "rolling_avg_30d": 488.23,
      "spike_ratio": 0.31,
      "is_spike": false
    },
    {
      "event_date": "2025-10-10",
      "avg_tone": -2.0535,
      "total_events": 149,
      "avg_conflict_score": 0.8738,
      "total_articles": 686,
      "rolling_avg_30d": 414.3,
      "spike_ratio": 0.36,
      "is_spike": false
    },
    {
      "event_date": "2025-10-11",
      "avg_tone": -2.3982,
      "total_events": 129,
      "avg_conflict_score": 1.1388,
      "total_articles": 449,
      "rolling_avg_30d": 354.47,
      "spike_ratio": 0.36,
      "is_spike": false
    },
    {
      "event_date": "2025-10-12",
      "avg_tone": -1.3521,
      "total_events": 171,
      "avg_conflict_score": 1.1094,
      "total_articles": 710,
      "rolling_avg_30d": 303.67,
      "spike_ratio": 0.56,
      "is_spike": false
    },
    {
      "event_date": "2025-10-13",
      "avg_tone": -1.9265,
      "total_events": 265,
      "avg_conflict_score": 0.786,
      "total_articles": 816,
      "rolling_avg_30d": 262.87,
      "spike_ratio": 1.01,
      "is_spike": false
    },
    {
      "event_date": "2025-10-14",
      "avg_tone": -3.1087,
      "total_events": 403,
      "avg_conflict_score": -0.3809,
      "total_articles": 1273,
      "rolling_avg_30d": 241.87,
      "spike_ratio": 1.67,
      "is_spike": false
    },
    {
      "event_date": "2025-10-15",
      "avg_tone": -3.3406,
      "total_events": 271,
      "avg_conflict_score": -0.317,
      "total_articles": 957,
      "rolling_avg_30d": 232.47,
      "spike_ratio": 1.17,
      "is_spike": false
    },
    {
      "event_date": "2025-10-16",
      "avg_tone": -1.1551,
      "total_events": 283,
      "avg_conflict_score": 1.0127,
      "total_articles": 1073,
      "rolling_avg_30d": 222.73,
      "spike_ratio": 1.27,
      "is_spike": false
    },
    {
      "event_date": "2025-10-17",
      "avg_tone": 0.6338,
      "total_events": 224,
      "avg_conflict_score": 1.8335,
      "total_articles": 817,
      "rolling_avg_30d": 216.63,
      "spike_ratio": 1.03,
      "is_spike": false
    },
    {
      "event_date": "2025-10-18",
      "avg_tone": -1.4333,
      "total_events": 186,
      "avg_conflict_score": 1.5785,
      "total_articles": 713,
      "rolling_avg_30d": 212.3,
      "spike_ratio": 0.88,
      "is_spike": false
    },
    {
      "event_date": "2025-10-19",
      "avg_tone": -1.3191,
      "total_events": 177,
      "avg_conflict_score": 1.8537,
      "total_articles": 682,
      "rolling_avg_30d": 205.33,
      "spike_ratio": 0.86,
      "is_spike": false
    },
    {
      "event_date": "2025-10-20",
      "avg_tone": -0.2088,
      "total_events": 316,
      "avg_conflict_score": 1.0377,
      "total_articles": 1167,
      "rolling_avg_30d": 194.67,
      "spike_ratio": 1.62,
      "is_spike": false
    },
    {
      "event_date": "2025-10-21",
      "avg_tone": -1.9157,
      "total_events": 225,
      "avg_conflict_score": 1.0164,
      "total_articles": 958,
      "rolling_avg_30d": 200.93,
      "spike_ratio": 1.12,
      "is_spike": false
    },
    {
      "event_date": "2025-10-22",
      "avg_tone": -0.8168,
      "total_events": 143,
      "avg_conflict_score": 0.6923,
      "total_articles": 569,
      "rolling_avg_30d": 201.03,
      "spike_ratio": 0.71,
      "is_spike": false
    },
    {
      "event_date": "2025-10-23",
      "avg_tone": -3.0118,
      "total_events": 129,
      "avg_conflict_score": -0.5798,
      "total_articles": 548,
      "rolling_avg_30d": 197.4,
      "spike_ratio": 0.65,
      "is_spike": false
    },
    {
      "event_date": "2025-10-24",
      "avg_tone": -0.4312,
      "total_events": 68,
      "avg_conflict_score": 0.2191,
      "total_articles": 343,
      "rolling_avg_30d": 194.33,
      "spike_ratio": 0.35,
      "is_spike": false
    },
    {
      "event_date": "2025-10-25",
      "avg_tone": -2.8387,
      "total_events": 118,
      "avg_conflict_score": -0.2305,
      "total_articles": 471,
      "rolling_avg_30d": 188.17,
      "spike_ratio": 0.63,
      "is_spike": false
    },
    {
      "event_date": "2025-10-26",
      "avg_tone": -0.2953,
      "total_events": 74,
      "avg_conflict_score": 1.5797,
      "total_articles": 286,
      "rolling_avg_30d": 184.13,
      "spike_ratio": 0.4,
      "is_spike": false
    },
    {
      "event_date": "2025-10-27",
      "avg_tone": -2.265,
      "total_events": 171,
      "avg_conflict_score": 0.283,
      "total_articles": 752,
      "rolling_avg_30d": 177.6,
      "spike_ratio": 0.96,
      "is_spike": false
    },
    {
      "event_date": "2025-10-28",
      "avg_tone": -1.6063,
      "total_events": 199,
      "avg_conflict_score": 0.4814,
      "total_articles": 995,
      "rolling_avg_30d": 178.63,
      "spike_ratio": 1.11,
      "is_spike": false
    },
    {
      "event_date": "2025-10-29",
      "avg_tone": -0.8547,
      "total_events": 307,
      "avg_conflict_score": 1.5876,
      "total_articles": 1274,
      "rolling_avg_30d": 180.7,
      "spike_ratio": 1.7,
      "is_spike": false
    },
    {
      "event_date": "2025-10-30",
      "avg_tone": -1.337,
      "total_events": 223,
      "avg_conflict_score": 1.9852,
      "total_articles": 887,
      "rolling_avg_30d": 185.37,
      "spike_ratio": 1.2,
      "is_spike": false
    },
    {
      "event_date": "2025-10-31",
      "avg_tone": -1.8703,
      "total_events": 293,
      "avg_conflict_score": 1.0413,
      "total_articles": 1124,
      "rolling_avg_30d": 187.9,
      "spike_ratio": 1.56,
      "is_spike": false
    },
    {
      "event_date": "2025-11-01",
      "avg_tone": -1.4675,
      "total_events": 120,
      "avg_conflict_score": 0.8267,
      "total_articles": 474,
      "rolling_avg_30d": 191.8,
      "spike_ratio": 0.63,
      "is_spike": false
    },
    {
      "event_date": "2025-11-02",
      "avg_tone": -1.9009,
      "total_events": 179,
      "avg_conflict_score": 0.7134,
      "total_articles": 764,
      "rolling_avg_30d": 190.9,
      "spike_ratio": 0.94,
      "is_spike": false
    },
    {
      "event_date": "2025-11-03",
      "avg_tone": -1.5755,
      "total_events": 272,
      "avg_conflict_score": 0.5066,
      "total_articles": 1132,
      "rolling_avg_30d": 193.53,
      "spike_ratio": 1.41,
      "is_spike": false
    },
    {
      "event_date": "2025-11-04",
      "avg_tone": -1.8396,
      "total_events": 250,
      "avg_conflict_score": 0.3852,
      "total_articles": 1012,
      "rolling_avg_30d": 198.63,
      "spike_ratio": 1.26,
      "is_spike": false
    },
    {
      "event_date": "2025-11-05",
      "avg_tone": -0.8725,
      "total_events": 304,
      "avg_conflict_score": 2.1171,
      "total_articles": 1219,
      "rolling_avg_30d": 201.57,
      "spike_ratio": 1.51,
      "is_spike": false
    },
    {
      "event_date": "2025-11-06",
      "avg_tone": -1.4197,
      "total_events": 253,
      "avg_conflict_score": 0.5383,
      "total_articles": 1008,
      "rolling_avg_30d": 206.0,
      "spike_ratio": 1.23,
      "is_spike": false
    },
    {
      "event_date": "2025-11-07",
      "avg_tone": -1.404,
      "total_events": 121,
      "avg_conflict_score": 0.0273,
      "total_articles": 475,
      "rolling_avg_30d": 207.93,
      "spike_ratio": 0.58,
      "is_spike": false
    },
    {
      "event_date": "2025-11-08",
      "avg_tone": -1.5874,
      "total_events": 128,
      "avg_conflict_score": 1.1281,
      "total_articles": 589,
      "rolling_avg_30d": 205.83,
      "spike_ratio": 0.62,
      "is_spike": false
    },
    {
      "event_date": "2025-11-09",
      "avg_tone": 0.107,
      "total_events": 146,
      "avg_conflict_score": 0.4651,
      "total_articles": 702,
      "rolling_avg_30d": 205.03,
      "spike_ratio": 0.71,
      "is_spike": false
    },
    {
      "event_date": "2025-11-10",
      "avg_tone": -1.2628,
      "total_events": 170,
      "avg_conflict_score": 0.1353,
      "total_articles": 726,
      "rolling_avg_30d": 204.93,
      "spike_ratio": 0.83,
      "is_spike": false
    },
    {
      "event_date": "2025-11-11",
      "avg_tone": -1.8004,
      "total_events": 230,
      "avg_conflict_score": 0.6278,
      "total_articles": 958,
      "rolling_avg_30d": 206.3,
      "spike_ratio": 1.11,
      "is_spike": false
    },
    {
      "event_date": "2025-11-12",
      "avg_tone": -1.6158,
      "total_events": 150,
      "avg_conflict_score": 1.128,
      "total_articles": 672,
      "rolling_avg_30d": 208.27,
      "spike_ratio": 0.72,
      "is_spike": false
    },
    {
      "event_date": "2025-11-13",
      "avg_tone": -0.9368,
      "total_events": 209,
      "avg_conflict_score": 2.1354,
      "total_articles": 893,
      "rolling_avg_30d": 204.43,
      "spike_ratio": 1.02,
      "is_spike": false
    },
    {
      "event_date": "2025-11-14",
      "avg_tone": 0.4011,
      "total_events": 197,
      "avg_conflict_score": 2.0284,
      "total_articles": 792,
      "rolling_avg_30d": 197.97,
      "spike_ratio": 1.0,
      "is_spike": false
    },
    {
      "event_date": "2025-11-15",
      "avg_tone": -1.0673,
      "total_events": 69,
      "avg_conflict_score": -0.2101,
      "total_articles": 280,
      "rolling_avg_30d": 195.5,
      "spike_ratio": 0.35,
      "is_spike": false
    }
  ],
  "countries": [
    {
      "Actor1CountryCode": "NPL",
      "event_count": 14556,
      "avg_tone": -3.6726
    },
    {
      "Actor1CountryCode": "IND",
      "event_count": 568,
      "avg_tone": -3.2543
    },
    {
      "Actor1CountryCode": "CHN",
      "event_count": 368,
      "avg_tone": -0.6106
    },
    {
      "Actor1CountryCode": "USA",
      "event_count": 285,
      "avg_tone": -2.3158
    },
    {
      "Actor1CountryCode": "ISR",
      "event_count": 277,
      "avg_tone": -4.3678
    },
    {
      "Actor1CountryCode": "BGD",
      "event_count": 242,
      "avg_tone": -1.7925
    },
    {
      "Actor1CountryCode": "PSE",
      "event_count": 105,
      "avg_tone": -4.2828
    },
    {
      "Actor1CountryCode": "PAK",
      "event_count": 98,
      "avg_tone": -2.3037
    },
    {
      "Actor1CountryCode": "GBR",
      "event_count": 92,
      "avg_tone": -1.574
    },
    {
      "Actor1CountryCode": "JPN",
      "event_count": 86,
      "avg_tone": -3.1485
    },
    {
      "Actor1CountryCode": "AUS",
      "event_count": 84,
      "avg_tone": -3.2114
    },
    {
      "Actor1CountryCode": "LKA",
      "event_count": 81,
      "avg_tone": -2.4516
    },
    {
      "Actor1CountryCode": "SDN",
      "event_count": 74,
      "avg_tone": -6.2214
    },
    {
      "Actor1CountryCode": "IDN",
      "event_count": 74,
      "avg_tone": -3.3311
    },
    {
      "Actor1CountryCode": "BTN",
      "event_count": 59,
      "avg_tone": 1.6426
    },
    {
      "Actor1CountryCode": "DEU",
      "event_count": 57,
      "avg_tone": -1.8757
    },
    {
      "Actor1CountryCode": "FRA",
      "event_count": 52,
      "avg_tone": -4.8244
    },
    {
      "Actor1CountryCode": "KOR",
      "event_count": 47,
      "avg_tone": -2.7228
    },
    {
      "Actor1CountryCode": "RUS",
      "event_count": 44,
      "avg_tone": -2.5782
    },
    {
      "Actor1CountryCode": "QAT",
      "event_count": 38,
      "avg_tone": -0.7115
    },
    {
      "Actor1CountryCode": "MDV",
      "event_count": 31,
      "avg_tone": -0.3692
    },
    {
      "Actor1CountryCode": "NGA",
      "event_count": 30,
      "avg_tone": -7.3841
    },
    {
      "Actor1CountryCode": "FIN",
      "event_count": 28,
      "avg_tone": -7.8176
    },
    {
      "Actor1CountryCode": "THA",
      "event_count": 26,
      "avg_tone": -2.1086
    },
    {
      "Actor1CountryCode": "PHL",
      "event_count": 26,
      "avg_tone": -3.9402
    },
    {
      "Actor1CountryCode": "ARE",
      "event_count": 25,
      "avg_tone": -6.704
    },
    {
      "Actor1CountryCode": "ITA",
      "event_count": 24,
      "avg_tone": -3.0341
    },
    {
      "Actor1CountryCode": "NOR",
      "event_count": 23,
      "avg_tone": -8.0473
    },
    {
      "Actor1CountryCode": "MDG",
      "event_count": 23,
      "avg_tone": -7.4169
    },
    {
      "Actor1CountryCode": "EUR",
      "event_count": 21,
      "avg_tone": 0.6263
    },
    {
      "Actor1CountryCode": "SAS",
      "event_count": 21,
      "avg_tone": -1.464
    },
    {
      "Actor1CountryCode": "CAN",
      "event_count": 20,
      "avg_tone": -1.7302
    },
    {
      "Actor1CountryCode": "SGP",
      "event_count": 20,
      "avg_tone": -1.0136
    },
    {
      "Actor1CountryCode": "MAR",
      "event_count": 17,
      "avg_tone": -6.8817
    },
    {
      "Actor1CountryCode": "IRN",
      "event_count": 17,
      "avg_tone": -0.5732
    },
    {
      "Actor1CountryCode": "CHE",
      "event_count": 17,
      "avg_tone": 3.3571
    },
    {
      "Actor1CountryCode": "IRL",
      "event_count": 16,
      "avg_tone": -0.7906
    },
    {
      "Actor1CountryCode": "BDI",
      "event_count": 14,
      "avg_tone": 6.6276
    },
    {
      "Actor1CountryCode": "MUS",
      "event_count": 14,
      "avg_tone": 0.0774
    },
    {
      "Actor1CountryCode": "NZL",
      "event_count": 13,
      "avg_tone": -1.3298
    },
    {
      "Actor1CountryCode": "AFG",
      "event_count": 11,
      "avg_tone": -0.5876
    },
    {
      "Actor1CountryCode": "AFR",
      "event_count": 11,
      "avg_tone": -2.6897
    },
    {
      "Actor1CountryCode": "MMR",
      "event_count": 11,
      "avg_tone": -0.9697
    },
    {
      "Actor1CountryCode": "ARM",
      "event_count": 10,
      "avg_tone": 1.6913
    },
    {
      "Actor1CountryCode": "TUR",
      "event_count": 10,
      "avg_tone": -8.6081
    },
    {
      "Actor1CountryCode": "VNM",
      "event_count": 10,
      "avg_tone": -0.3611
    },
    {
      "Actor1CountryCode": "MYS",
      "event_count": 10,
      "avg_tone": -1.7434
    },
    {
      "Actor1CountryCode": "KEN",
      "event_count": 9,
      "avg_tone": -4.2484
    },
    {
      "Actor1CountryCode": "POL",
      "event_count": 8,
      "avg_tone": 1.3598
    },
    {
      "Actor1CountryCode": "MNG",
      "event_count": 8,
      "avg_tone": -1.8412
    },
    {
      "Actor1CountryCode": "TZA",
      "event_count": 8,
      "avg_tone": 7.07
    },
    {
      "Actor1CountryCode": "UKR",
      "event_count": 7,
      "avg_tone": -4.0502
    },
    {
      "Actor1CountryCode": "CZE",
      "event_count": 7,
      "avg_tone": -4.2364
    },
    {
      "Actor1CountryCode": "LAO",
      "event_count": 6,
      "avg_tone": 0.8513
    },
    {
      "Actor1CountryCode": "AGO",
      "event_count": 6,
      "avg_tone": 2.4896
    },
    {
      "Actor1CountryCode": "EGY",
      "event_count": 6,
      "avg_tone": -1.9276
    },
    {
      "Actor1CountryCode": "BRA",
      "event_count": 5,
      "avg_tone": 0.1817
    },
    {
      "Actor1CountryCode": "TWN",
      "event_count": 5,
      "avg_tone": -1.0329
    },
    {
      "Actor1CountryCode": "BEL",
      "event_count": 5,
      "avg_tone": 1.9121
    },
    {
      "Actor1CountryCode": "TMP",
      "event_count": 5,
      "avg_tone": -6.4351
    },
    {
      "Actor1CountryCode": "UZB",
      "event_count": 5,
      "avg_tone": -1.9127
    },
    {
      "Actor1CountryCode": "GHA",
      "event_count": 5,
      "avg_tone": 2.4843
    },
    {
      "Actor1CountryCode": "ASA",
      "event_count": 4,
      "avg_tone": -4.3279
    },
    {
      "Actor1CountryCode": "GRC",
      "event_count": 4,
      "avg_tone": -3.9056
    },
    {
      "Actor1CountryCode": "ETH",
      "event_count": 4,
      "avg_tone": 7.07
    },
    {
      "Actor1CountryCode": "SEN",
      "event_count": 4,
      "avg_tone": 4.9229
    },
    {
      "Actor1CountryCode": "KNA",
      "event_count": 4,
      "avg_tone": -0.5999
    },
    {
      "Actor1CountryCode": "IRQ",
      "event_count": 3,
      "avg_tone": -1.1755
    },
    {
      "Actor1CountryCode": "VEN",
      "event_count": 3,
      "avg_tone": 2.4896
    },
    {
      "Actor1CountryCode": "CYP",
      "event_count": 3,
      "avg_tone": -5.6604
    },
    {
      "Actor1CountryCode": "KHM",
      "event_count": 3,
      "avg_tone": 0.2296
    },
    {
      "Actor1CountryCode": "HTI",
      "event_count": 3,
      "avg_tone": -5.922
    },
    {
      "Actor1CountryCode": "SRB",
      "event_count": 3,
      "avg_tone": -0.7353
    },
    {
      "Actor1CountryCode": "NMR",
      "event_count": 3,
      "avg_tone": 5.5529
    },
    {
      "Actor1CountryCode": "PER",
      "event_count": 3,
      "avg_tone": -8.2676
    },
    {
      "Actor1CountryCode": "KAZ",
      "event_count": 3,
      "avg_tone": 1.43
    },
    {
      "Actor1CountryCode": "ISL",
      "event_count": 3,
      "avg_tone": 2.8101
    },
    {
      "Actor1CountryCode": "JOR",
      "event_count": 3,
      "avg_tone": -2.0971
    },
    {
      "Actor1CountryCode": "CUB",
      "event_count": 2,
      "avg_tone": -5.906
    },
    {
      "Actor1CountryCode": "LBY",
      "event_count": 2,
      "avg_tone": -8.8553
    },
    {
      "Actor1CountryCode": "TKM",
      "event_count": 2,
      "avg_tone": 0.3868
    },
    {
      "Actor1CountryCode": "OMN",
      "event_count": 2,
      "avg_tone": -3.4382
    },
    {
      "Actor1CountryCode": "SLB",
      "event_count": 2,
      "avg_tone": -0.0883
    },
    {
      "Actor1CountryCode": "VAT",
      "event_count": 2,
      "avg_tone": 1.8703
    },
    {
      "Actor1CountryCode": "YEM",
      "event_count": 2,
      "avg_tone": -1.9788
    },
    {
      "Actor1CountryCode": "RWA",
      "event_count": 2,
      "avg_tone": 2.0816
    },
    {
      "Actor1CountryCode": "WST",
      "event_count": 2,
      "avg_tone": 0.5013
    },
    {
      "Actor1CountryCode": "ESP",
      "event_count": 2,
      "avg_tone": 5.1945
    },
    {
      "Actor1CountryCode": "CRB",
      "event_count": 2,
      "avg_tone": -4.5761
    },
    {
      "Actor1CountryCode": "KWT",
      "event_count": 2,
      "avg_tone": -3.5413
    },
    {
      "Actor1CountryCode": "ARG",
      "event_count": 2,
      "avg_tone": 8.0
    },
    {
      "Actor1CountryCode": "MLT",
      "event_count": 1,
      "avg_tone": -9.5618
    },
    {
      "Actor1CountryCode": "LBN",
      "event_count": 1,
      "avg_tone": -5.9061
    },
    {
      "Actor1CountryCode": "SAU",
      "event_count": 1,
      "avg_tone": -2.9925
    },
    {
      "Actor1CountryCode": "AZE",
      "event_count": 1,
      "avg_tone": 4.8159
    },
    {
      "Actor1CountryCode": "DNK",
      "event_count": 1,
      "avg_tone": 0.0983
    }
  ],
  "quadclass": [
    {
      "period": 2015,
      "QuadClass": 3,
      "count": 6504,
      "period_total": 49873,
      "percentage": 13.04
    },
    {
      "period": 2015,
      "QuadClass": 1,
      "count": 31247,
      "period_total": 49873,
      "percentage": 62.65
    },
    {
      "period": 2015,
      "QuadClass": 4,
      "count": 7035,
      "period_total": 49873,
      "percentage": 14.11
    },
    {
      "period": 2015,
      "QuadClass": 2,
      "count": 5087,
      "period_total": 49873,
      "percentage": 10.2
    },
    {
      "period": 2025,
      "QuadClass": 3,
      "count": 3302,
      "period_total": 24503,
      "percentage": 13.48
    },
    {
      "period": 2025,
      "QuadClass": 1,
      "count": 13747,
      "period_total": 24503,
      "percentage": 56.1
    },
    {
      "period": 2025,
      "QuadClass": 4,
      "count": 4338,
      "period_total": 24503,
      "percentage": 17.7
    },
    {
      "period": 2025,
      "QuadClass": 2,
      "count": 3116,
      "period_total": 24503,
      "percentage": 12.72
    }
  ],
  "timeline": [
    {
      "days_since_start": -9,
      "avg_tone": -1.9916,
      "total_events": 239,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -8,
      "avg_tone": -2.1895,
      "total_events": 419,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -7,
      "avg_tone": -2.4576,
      "total_events": 374,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -7,
      "avg_tone": -1.2954,
      "total_events": 221,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": -6,
      "avg_tone": -2.8663,
      "total_events": 402,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -6,
      "avg_tone": -1.4363,
      "total_events": 184,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": -5,
      "avg_tone": -3.4133,
      "total_events": 459,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -5,
      "avg_tone": -0.3253,
      "total_events": 272,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": -4,
      "avg_tone": -1.7775,
      "total_events": 465,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -4,
      "avg_tone": -1.3179,
      "total_events": 299,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": -3,
      "avg_tone": -1.4304,
      "total_events": 485,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -3,
      "avg_tone": -1.8522,
      "total_events": 233,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": -2,
      "avg_tone": -2.3241,
      "total_events": 391,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -2,
      "avg_tone": 0.5569,
      "total_events": 188,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": -1,
      "avg_tone": -1.7916,
      "total_events": 586,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -1,
      "avg_tone": -1.6002,
      "total_events": 172,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 0,
      "avg_tone": -3.6907,
      "total_events": 811,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 0,
      "avg_tone": -7.6609,
      "total_events": 675,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 1,
      "avg_tone": -4.6961,
      "total_events": 931,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 1,
      "avg_tone": -8.1429,
      "total_events": 2370,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 2,
      "avg_tone": -2.6956,
      "total_events": 717,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 2,
      "avg_tone": -5.9853,
      "total_events": 1944,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 3,
      "avg_tone": -2.4439,
      "total_events": 551,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 3,
      "avg_tone": -4.7834,
      "total_events": 1653,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 4,
      "avg_tone": -2.1038,
      "total_events": 544,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 4,
      "avg_tone": -4.6002,
      "total_events": 1395,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 5,
      "avg_tone": -1.9468,
      "total_events": 229,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 5,
      "avg_tone": -2.8716,
      "total_events": 895,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 6,
      "avg_tone": -2.4242,
      "total_events": 268,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 6,
      "avg_tone": -3.4076,
      "total_events": 685,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 7,
      "avg_tone": -2.4693,
      "total_events": 426,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 7,
      "avg_tone": -4.309,
      "total_events": 563,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 8,
      "avg_tone": -4.193,
      "total_events": 431,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 8,
      "avg_tone": -5.0717,
      "total_events": 466,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 9,
      "avg_tone": -3.2728,
      "total_events": 572,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 9,
      "avg_tone": -2.3078,
      "total_events": 354,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 10,
      "avg_tone": -2.4024,
      "total_events": 383,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 10,
      "avg_tone": -1.4195,
      "total_events": 395,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 11,
      "avg_tone": -1.9672,
      "total_events": 459,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 11,
      "avg_tone": -1.7149,
      "total_events": 497,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 12,
      "avg_tone": -2.4814,
      "total_events": 304,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 12,
      "avg_tone": -3.3307,
      "total_events": 128,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 13,
      "avg_tone": -2.364,
      "total_events": 238,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 13,
      "avg_tone": -1.8293,
      "total_events": 222,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 14,
      "avg_tone": -3.1354,
      "total_events": 465,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 14,
      "avg_tone": -1.5595,
      "total_events": 252,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 15,
      "avg_tone": -2.6583,
      "total_events": 595,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 15,
      "avg_tone": -1.0647,
      "total_events": 221,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 16,
      "avg_tone": -3.0221,
      "total_events": 1061,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 16,
      "avg_tone": -2.4574,
      "total_events": 253,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 17,
      "avg_tone": -3.3071,
      "total_events": 822,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 17,
      "avg_tone": -4.2233,
      "total_events": 239,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 18,
      "avg_tone": -3.2526,
      "total_events": 704,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 18,
      "avg_tone": -2.7812,
      "total_events": 270,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 19,
      "avg_tone": -2.9357,
      "total_events": 460,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 19,
      "avg_tone": -4.9496,
      "total_events": 140,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 20,
      "avg_tone": -3.0518,
      "total_events": 431,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 20,
      "avg_tone": -4.0509,
      "total_events": 137,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 21,
      "avg_tone": -2.752,
      "total_events": 566,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 21,
      "avg_tone": -4.0615,
      "total_events": 167,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 22,
      "avg_tone": -2.3704,
      "total_events": 562,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 22,
      "avg_tone": -2.9779,
      "total_events": 147,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 23,
      "avg_tone": -2.1378,
      "total_events": 565,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 23,
      "avg_tone": -2.2722,
      "total_events": 176,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 24,
      "avg_tone": -2.8341,
      "total_events": 753,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 24,
      "avg_tone": -1.4021,
      "total_events": 147,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 25,
      "avg_tone": -1.7122,
      "total_events": 733,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 25,
      "avg_tone": -2.547,
      "total_events": 100,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 26,
      "avg_tone": -0.8726,
      "total_events": 455,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 26,
      "avg_tone": -1.7706,
      "total_events": 119,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 27,
      "avg_tone": -1.567,
      "total_events": 694,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 27,
      "avg_tone": -6.2266,
      "total_events": 162,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 28,
      "avg_tone": -2.1693,
      "total_events": 791,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 28,
      "avg_tone": -3.603,
      "total_events": 171,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 29,
      "avg_tone": -2.3197,
      "total_events": 828,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 29,
      "avg_tone": -3.9491,
      "total_events": 195,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 30,
      "avg_tone": -2.2355,
      "total_events": 780,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 30,
      "avg_tone": -2.0008,
      "total_events": 184,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 31,
      "avg_tone": -2.7766,
      "total_events": 696,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 31,
      "avg_tone": -1.7419,
      "total_events": 152,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 32,
      "avg_tone": -3.0225,
      "total_events": 721,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 32,
      "avg_tone": -2.0535,
      "total_events": 149,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 33,
      "avg_tone": -2.5296,
      "total_events": 636,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 33,
      "avg_tone": -2.3982,
      "total_events": 129,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 34,
      "avg_tone": -2.7477,
      "total_events": 462,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 34,
      "avg_tone": -1.3521,
      "total_events": 171,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 35,
      "avg_tone": -2.5755,
      "total_events": 647,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 35,
      "avg_tone": -1.9265,
      "total_events": 265,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 36,
      "avg_tone": -2.1311,
      "total_events": 717,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 36,
      "avg_tone": -3.1087,
      "total_events": 403,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 37,
      "avg_tone": -2.0202,
      "total_events": 795,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 37,
      "avg_tone": -3.3406,
      "total_events": 271,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 38,
      "avg_tone": -2.5489,
      "total_events": 697,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 38,
      "avg_tone": -1.1551,
      "total_events": 283,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 39,
      "avg_tone": -2.6267,
      "total_events": 564,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 39,
      "avg_tone": 0.6338,
      "total_events": 224,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 40,
      "avg_tone": -2.7158,
      "total_events": 467,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 40,
      "avg_tone": -1.4333,
      "total_events": 186,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 41,
      "avg_tone": -2.0259,
      "total_events": 469,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 41,
      "avg_tone": -1.3191,
      "total_events": 177,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 42,
      "avg_tone": -2.5117,
      "total_events": 606,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 42,
      "avg_tone": -0.2088,
      "total_events": 316,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 43,
      "avg_tone": -2.1248,
      "total_events": 560,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 43,
      "avg_tone": -1.9157,
      "total_events": 225,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 44,
      "avg_tone": -2.8188,
      "total_events": 587,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 44,
      "avg_tone": -0.8168,
      "total_events": 143,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 45,
      "avg_tone": -2.1822,
      "total_events": 606,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 45,
      "avg_tone": -3.0118,
      "total_events": 129,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 46,
      "avg_tone": -2.2489,
      "total_events": 680,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 46,
      "avg_tone": -0.4312,
      "total_events": 68,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 47,
      "avg_tone": -1.9312,
      "total_events": 437,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 47,
      "avg_tone": -2.8387,
      "total_events": 118,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 48,
      "avg_tone": -1.613,
      "total_events": 497,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 48,
      "avg_tone": -0.2953,
      "total_events": 74,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 49,
      "avg_tone": -0.8746,
      "total_events": 486,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 49,
      "avg_tone": -2.265,
      "total_events": 171,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 50,
      "avg_tone": -1.2354,
      "total_events": 433,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 50,
      "avg_tone": -1.6063,
      "total_events": 199,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 51,
      "avg_tone": -1.6649,
      "total_events": 501,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 51,
      "avg_tone": -0.8547,
      "total_events": 307,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 52,
      "avg_tone": -1.4418,
      "total_events": 482,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 52,
      "avg_tone": -1.337,
      "total_events": 223,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 53,
      "avg_tone": -3.4717,
      "total_events": 570,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 53,
      "avg_tone": -1.8703,
      "total_events": 293,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 54,
      "avg_tone": -1.9946,
      "total_events": 371,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 54,
      "avg_tone": -1.4675,
      "total_events": 120,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 55,
      "avg_tone": -2.5563,
      "total_events": 370,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 55,
      "avg_tone": -1.9009,
      "total_events": 179,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 56,
      "avg_tone": -1.857,
      "total_events": 571,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 56,
      "avg_tone": -1.5755,
      "total_events": 272,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 57,
      "avg_tone": -1.4825,
      "total_events": 492,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 57,
      "avg_tone": -1.8396,
      "total_events": 250,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 58,
      "avg_tone": -1.0806,
      "total_events": 60,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 58,
      "avg_tone": -0.8725,
      "total_events": 304,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 59,
      "avg_tone": -1.9589,
      "total_events": 46,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 59,
      "avg_tone": -1.4197,
      "total_events": 253,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 60,
      "avg_tone": -1.1175,
      "total_events": 306,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 60,
      "avg_tone": -1.404,
      "total_events": 121,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 61,
      "avg_tone": -3.0132,
      "total_events": 350,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 61,
      "avg_tone": -1.5874,
      "total_events": 128,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 62,
      "avg_tone": -2.1953,
      "total_events": 329,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 62,
      "avg_tone": 0.107,
      "total_events": 146,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 63,
      "avg_tone": -2.1629,
      "total_events": 473,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 63,
      "avg_tone": -1.2628,
      "total_events": 170,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 64,
      "avg_tone": -1.5068,
      "total_events": 489,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 64,
      "avg_tone": -1.8004,
      "total_events": 230,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 65,
      "avg_tone": -1.4699,
      "total_events": 563,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 65,
      "avg_tone": -1.6158,
      "total_events": 150,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 66,
      "avg_tone": -1.5709,
      "total_events": 758,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 66,
      "avg_tone": -0.9368,
      "total_events": 209,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 67,
      "avg_tone": -1.8778,
      "total_events": 662,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 67,
      "avg_tone": 0.4011,
      "total_events": 197,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 68,
      "avg_tone": -1.6955,
      "total_events": 407,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 68,
      "avg_tone": -1.0673,
      "total_events": 69,
      "period": "2025 Gen-Z Protest"
    },
    {
      "days_since_start": 69,
      "avg_tone": -1.7845,
      "total_events": 395,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 70,
      "avg_tone": -5.6521,
      "total_events": 1180,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 71,
      "avg_tone": -4.6189,
      "total_events": 885,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 72,
      "avg_tone": -2.3202,
      "total_events": 738,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 73,
      "avg_tone": -2.0956,
      "total_events": 535,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 74,
      "avg_tone": -2.7098,
      "total_events": 639,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 75,
      "avg_tone": -2.8289,
      "total_events": 412,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 76,
      "avg_tone": -3.4147,
      "total_events": 612,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 77,
      "avg_tone": -2.8703,
      "total_events": 501,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 78,
      "avg_tone": -1.7769,
      "total_events": 422,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 79,
      "avg_tone": -1.7515,
      "total_events": 400,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 80,
      "avg_tone": -1.6694,
      "total_events": 296,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 81,
      "avg_tone": -1.3943,
      "total_events": 290,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 82,
      "avg_tone": -1.8456,
      "total_events": 255,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": 83,
      "avg_tone": -2.5372,
      "total_events": 287,
      "period": "2015 Blockade"
    },
    {
      "days_since_start": -10,
      "avg_tone": -0.5098,
      "total_events": 257,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -9,
      "avg_tone": -0.1353,
      "total_events": 316,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -8,
      "avg_tone": -0.8003,
      "total_events": 359,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -7,
      "avg_tone": -1.8334,
      "total_events": 196,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -6,
      "avg_tone": -2.7111,
      "total_events": 254,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -5,
      "avg_tone": -0.8487,
      "total_events": 268,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -4,
      "avg_tone": -1.2536,
      "total_events": 301,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -3,
      "avg_tone": -3.8776,
      "total_events": 597,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -2,
      "avg_tone": -2.2518,
      "total_events": 443,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": -1,
      "avg_tone": -0.3348,
      "total_events": 427,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 0,
      "avg_tone": -3.8217,
      "total_events": 2886,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 1,
      "avg_tone": -2.5406,
      "total_events": 5089,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 2,
      "avg_tone": -2.0017,
      "total_events": 7190,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 3,
      "avg_tone": -1.8065,
      "total_events": 5993,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 4,
      "avg_tone": -1.966,
      "total_events": 4994,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 5,
      "avg_tone": -1.5582,
      "total_events": 4243,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 6,
      "avg_tone": -1.6334,
      "total_events": 3324,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 7,
      "avg_tone": -1.6656,
      "total_events": 1985,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 8,
      "avg_tone": -1.5104,
      "total_events": 1902,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 9,
      "avg_tone": -1.2581,
      "total_events": 2403,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 10,
      "avg_tone": -0.9522,
      "total_events": 1919,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 11,
      "avg_tone": -1.2281,
      "total_events": 1512,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 12,
      "avg_tone": -1.0765,
      "total_events": 1362,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 13,
      "avg_tone": -0.8068,
      "total_events": 1167,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 14,
      "avg_tone": -0.7056,
      "total_events": 697,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 15,
      "avg_tone": -0.6798,
      "total_events": 634,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 16,
      "avg_tone": -1.0667,
      "total_events": 929,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 17,
      "avg_tone": -3.3004,
      "total_events": 2133,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 18,
      "avg_tone": -3.1992,
      "total_events": 1692,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 19,
      "avg_tone": -2.2113,
      "total_events": 1240,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 20,
      "avg_tone": -2.0273,
      "total_events": 1273,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 21,
      "avg_tone": -2.024,
      "total_events": 718,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 22,
      "avg_tone": -1.7168,
      "total_events": 519,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 23,
      "avg_tone": -1.009,
      "total_events": 632,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 24,
      "avg_tone": -1.4901,
      "total_events": 640,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 25,
      "avg_tone": -0.4604,
      "total_events": 648,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 26,
      "avg_tone": -0.8082,
      "total_events": 703,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 27,
      "avg_tone": -1.2535,
      "total_events": 599,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 28,
      "avg_tone": -1.5485,
      "total_events": 347,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 29,
      "avg_tone": -2.1344,
      "total_events": 434,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 30,
      "avg_tone": -1.6485,
      "total_events": 499,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 31,
      "avg_tone": -0.892,
      "total_events": 551,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 32,
      "avg_tone": -0.8051,
      "total_events": 597,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 33,
      "avg_tone": -0.6042,
      "total_events": 466,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 34,
      "avg_tone": -1.3039,
      "total_events": 545,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 35,
      "avg_tone": -2.2532,
      "total_events": 278,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 36,
      "avg_tone": -1.5112,
      "total_events": 260,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 37,
      "avg_tone": -0.692,
      "total_events": 376,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 38,
      "avg_tone": -1.5666,
      "total_events": 447,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 39,
      "avg_tone": -1.5972,
      "total_events": 356,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 40,
      "avg_tone": -0.8581,
      "total_events": 427,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 41,
      "avg_tone": -1.0925,
      "total_events": 469,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 42,
      "avg_tone": -1.8311,
      "total_events": 308,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 43,
      "avg_tone": -1.5006,
      "total_events": 311,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 44,
      "avg_tone": -1.4165,
      "total_events": 609,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 45,
      "avg_tone": -0.9484,
      "total_events": 596,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 46,
      "avg_tone": -0.1782,
      "total_events": 655,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 47,
      "avg_tone": 0.2042,
      "total_events": 618,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 48,
      "avg_tone": -0.0674,
      "total_events": 505,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 49,
      "avg_tone": -0.7787,
      "total_events": 236,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 50,
      "avg_tone": -1.7786,
      "total_events": 327,
      "period": "2015 Earthquake"
    },
    {
      "days_since_start": 51,
      "avg_tone": -0.2338,
      "total_events": 487,
      "period": "2015 Earthquake"
    }
  ],
  "indiaChina": [
    {
      "event_date": "2024-11-03",
      "india_tone": -3.428,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-08-31",
      "india_tone": -7.5697,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-09-01",
      "india_tone": -5.1967,
      "india_event_count": 11.0,
      "china_tone": 2.3698,
      "china_event_count": 12.0
    },
    {
      "event_date": "2025-09-02",
      "india_tone": null,
      "india_event_count": null,
      "china_tone": 1.1169,
      "china_event_count": 8.0
    },
    {
      "event_date": "2025-09-03",
      "india_tone": -6.4473,
      "india_event_count": 2.0,
      "china_tone": 0.9506,
      "china_event_count": 17.0
    },
    {
      "event_date": "2025-09-04",
      "india_tone": -2.5003,
      "india_event_count": 4.0,
      "china_tone": 1.5748,
      "china_event_count": 12.0
    },
    {
      "event_date": "2025-09-05",
      "india_tone": -3.4036,
      "india_event_count": 7.0,
      "china_tone": 0.5961,
      "china_event_count": 6.0
    },
    {
      "event_date": "2025-09-06",
      "india_tone": 2.9773,
      "india_event_count": 3.0,
      "china_tone": -1.7011,
      "china_event_count": 4.0
    },
    {
      "event_date": "2025-09-07",
      "india_tone": null,
      "india_event_count": null,
      "china_tone": 0.8661,
      "china_event_count": 8.0
    },
    {
      "event_date": "2025-09-08",
      "india_tone": -7.4066,
      "india_event_count": 2.0,
      "china_tone": 0.0,
      "china_event_count": 4.0
    },
    {
      "event_date": "2025-09-09",
      "india_tone": -5.9584,
      "india_event_count": 70.0,
      "china_tone": -4.7205,
      "china_event_count": 15.0
    },
    {
      "event_date": "2025-09-10",
      "india_tone": -4.3494,
      "india_event_count": 103.0,
      "china_tone": -5.6158,
      "china_event_count": 15.0
    },
    {
      "event_date": "2025-09-11",
      "india_tone": -3.7201,
      "india_event_count": 44.0,
      "china_tone": -3.3088,
      "china_event_count": 19.0
    },
    {
      "event_date": "2025-09-12",
      "india_tone": -3.5519,
      "india_event_count": 34.0,
      "china_tone": -3.7721,
      "china_event_count": 12.0
    },
    {
      "event_date": "2025-09-13",
      "india_tone": 0.0758,
      "india_event_count": 46.0,
      "china_tone": -5.9178,
      "china_event_count": 6.0
    },
    {
      "event_date": "2025-09-14",
      "india_tone": 0.2875,
      "india_event_count": 5.0,
      "china_tone": 0.4348,
      "china_event_count": 60.0
    },
    {
      "event_date": "2025-09-15",
      "india_tone": -4.2224,
      "india_event_count": 7.0,
      "china_tone": 0.3192,
      "china_event_count": 20.0
    },
    {
      "event_date": "2025-09-16",
      "india_tone": -10.2516,
      "india_event_count": 12.0,
      "china_tone": -1.1933,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-09-17",
      "india_tone": 0.7538,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-09-18",
      "india_tone": 1.575,
      "india_event_count": 3.0,
      "china_tone": 10.2564,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-09-19",
      "india_tone": -4.5231,
      "india_event_count": 4.0,
      "china_tone": 2.9689,
      "china_event_count": 22.0
    },
    {
      "event_date": "2025-09-20",
      "india_tone": -2.9772,
      "india_event_count": 2.0,
      "china_tone": 11.6162,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-09-21",
      "india_tone": -3.4986,
      "india_event_count": 9.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-09-22",
      "india_tone": -0.2982,
      "india_event_count": 5.0,
      "china_tone": 4.3283,
      "china_event_count": 3.0
    },
    {
      "event_date": "2025-09-23",
      "india_tone": 7.6523,
      "india_event_count": 2.0,
      "china_tone": -0.7987,
      "china_event_count": 20.0
    },
    {
      "event_date": "2025-09-24",
      "india_tone": -0.1136,
      "india_event_count": 3.0,
      "china_tone": -0.1661,
      "china_event_count": 3.0
    },
    {
      "event_date": "2025-09-25",
      "india_tone": -1.4762,
      "india_event_count": 14.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-09-26",
      "india_tone": -5.0228,
      "india_event_count": 2.0,
      "china_tone": -1.7827,
      "china_event_count": 8.0
    },
    {
      "event_date": "2025-09-27",
      "india_tone": -12.4031,
      "india_event_count": 1.0,
      "china_tone": 3.504,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-09-28",
      "india_tone": -4.5487,
      "india_event_count": 3.0,
      "china_tone": -0.2247,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-09-29",
      "india_tone": -2.3026,
      "india_event_count": 2.0,
      "china_tone": -8.8435,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-09-30",
      "india_tone": 4.9002,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-01",
      "india_tone": -5.0847,
      "india_event_count": 2.0,
      "china_tone": -4.0195,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-10-02",
      "india_tone": -3.4579,
      "india_event_count": 5.0,
      "china_tone": -2.3422,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-10-03",
      "india_tone": -2.6203,
      "india_event_count": 3.0,
      "china_tone": -2.449,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-10-04",
      "india_tone": -2.2489,
      "india_event_count": 2.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-05",
      "india_tone": -7.1823,
      "india_event_count": 3.0,
      "china_tone": -6.1834,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-10-06",
      "india_tone": -4.7837,
      "india_event_count": 2.0,
      "china_tone": -0.4329,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-10-07",
      "india_tone": -8.5499,
      "india_event_count": 14.0,
      "china_tone": -2.1896,
      "china_event_count": 3.0
    },
    {
      "event_date": "2025-10-08",
      "india_tone": null,
      "india_event_count": null,
      "china_tone": -0.7618,
      "china_event_count": 4.0
    },
    {
      "event_date": "2025-10-09",
      "india_tone": -1.3245,
      "india_event_count": 3.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-10",
      "india_tone": -0.1307,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-11",
      "india_tone": 1.5256,
      "india_event_count": 3.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-12",
      "india_tone": -5.9192,
      "india_event_count": 5.0,
      "china_tone": -0.2448,
      "china_event_count": 13.0
    },
    {
      "event_date": "2025-10-13",
      "india_tone": -8.4867,
      "india_event_count": 3.0,
      "china_tone": -4.0,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-10-14",
      "india_tone": 1.3123,
      "india_event_count": 2.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-16",
      "india_tone": 5.9172,
      "india_event_count": 2.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-17",
      "india_tone": 0.9946,
      "india_event_count": 6.0,
      "china_tone": -0.258,
      "china_event_count": 3.0
    },
    {
      "event_date": "2025-10-18",
      "india_tone": -1.5228,
      "india_event_count": 17.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-19",
      "india_tone": -0.4924,
      "india_event_count": 3.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-20",
      "india_tone": 6.5217,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-21",
      "india_tone": null,
      "india_event_count": null,
      "china_tone": -1.8685,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-10-22",
      "india_tone": 7.2495,
      "india_event_count": 1.0,
      "china_tone": -0.6703,
      "china_event_count": 3.0
    },
    {
      "event_date": "2025-10-26",
      "india_tone": null,
      "india_event_count": null,
      "china_tone": -3.0498,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-10-27",
      "india_tone": -1.4119,
      "india_event_count": 6.0,
      "china_tone": 8.4967,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-10-28",
      "india_tone": 2.35,
      "india_event_count": 7.0,
      "china_tone": -2.8571,
      "china_event_count": 1.0
    },
    {
      "event_date": "2025-10-29",
      "india_tone": 1.8041,
      "india_event_count": 9.0,
      "china_tone": -0.2388,
      "china_event_count": 3.0
    },
    {
      "event_date": "2025-10-30",
      "india_tone": 1.9938,
      "india_event_count": 3.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-10-31",
      "india_tone": -5.5051,
      "india_event_count": 6.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-01",
      "india_tone": -2.9899,
      "india_event_count": 12.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-02",
      "india_tone": -3.2469,
      "india_event_count": 3.0,
      "china_tone": -3.7611,
      "china_event_count": 4.0
    },
    {
      "event_date": "2025-11-03",
      "india_tone": -6.9959,
      "india_event_count": 1.0,
      "china_tone": 5.5848,
      "china_event_count": 4.0
    },
    {
      "event_date": "2025-11-04",
      "india_tone": -9.596,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-05",
      "india_tone": null,
      "india_event_count": null,
      "china_tone": -1.708,
      "china_event_count": 8.0
    },
    {
      "event_date": "2025-11-06",
      "india_tone": -1.8338,
      "india_event_count": 7.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-07",
      "india_tone": -1.9108,
      "india_event_count": 1.0,
      "china_tone": 1.1375,
      "china_event_count": 5.0
    },
    {
      "event_date": "2025-11-09",
      "india_tone": -3.4926,
      "india_event_count": 5.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-10",
      "india_tone": -1.5038,
      "india_event_count": 2.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-11",
      "india_tone": -2.1607,
      "india_event_count": 7.0,
      "china_tone": -9.3694,
      "china_event_count": 2.0
    },
    {
      "event_date": "2025-11-12",
      "india_tone": -7.0588,
      "india_event_count": 1.0,
      "china_tone": null,
      "china_event_count": null
    },
    {
      "event_date": "2025-11-13",
      "india_tone": 1.9143,
      "india_event_count": 8.0,
      "china_tone": -6.3615,
      "china_event_count": 6.0
    },
    {
      "event_date": "2025-11-14",
      "india_tone": 4.8996,
      "india_event_count": 4.0,
      "china_tone": -4.0387,
      "china_event_count": 6.0
    },
    {
      "event_date": "2025-11-15",
      "india_tone": -3.8428,
      "india_event_count": 3.0,
      "china_tone": 3.1839,
      "china_event_count": 5.0
    }
  ],
  "summary": {
    "india_mean": -2.33,
    "china_mean": -0.48,
    "ttest_incident": {
      "t": -13.95,
      "p": 0.0051,
      "n": 3
    },
    "ttest_daily": {
      "t": -2.26,
      "p": 0.0291,
      "n": 44
    },
    "correlation": {
      "r": -0.0235,
      "p": 0.8795,
      "n": 44
    },
    "sept9": {
      "india_events": 70,
      "global_events": 2370,
      "spike_ratio": 30.99,
      "baseline": 3
    },
    "incident_tones": {
      "India": {
        "2015 Earthquake": -2.2623,
        "2015 Blockade": -2.4345,
        "2025 Gen-Z Protest": -2.2958
      },
      "China": {
        "2015 Earthquake": -0.2866,
        "2015 Blockade": -0.445,
        "2025 Gen-Z Protest": -0.7109
      }
    },
    "china_drift": [
      -0.2866,
      -0.445,
      -0.7109
    ],
    "verbal_coop": {
      "2015": 62.65,
      "2025": 56.1
    },
    "material_conflict": {
      "2015": 14.11,
      "2025": 17.7
    },
    "bhutan_tone": 1.6426
  }
};
